# Generated by Django 3.1.3 on 2021-01-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='add_by',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='delete_by',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='delete_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
