# Generated by Django 3.1.3 on 2021-01-05 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_session_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('login_time', models.DateTimeField(default=datetime.datetime.now)),
                ('ip', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
