# Generated by Django 3.1.3 on 2020-12-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='usage_reason',
            field=models.CharField(max_length=300),
        ),
    ]
