# Generated by Django 3.1.3 on 2021-01-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0002_auto_20201231_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='cancel_by',
            field=models.IntegerField(default=0),
        ),
    ]
