# Generated by Django 3.1.3 on 2020-12-31 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place_Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('place_id_list', models.CharField(max_length=50)),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
                ('update_time', models.DateTimeField(default=datetime.datetime.now)),
                ('delete_time', models.DateTimeField(blank=True, null=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='place',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
