# Generated by Django 3.1.3 on 2021-01-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_auto_20210103_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='add_by',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='place',
            name='delete_by',
            field=models.IntegerField(default=0),
        ),
    ]
